### ISSUE TITLE
Missing image assets

### ISSUE THREAD

**Issue by chris-c-thomas** [sindresorhus/generate-github-markdown-css#20]
Viewing the rendered example isn't displaying the asset.

<img width="1134" alt="Screenshot 2023-02-10 at 8 16 01 AM" src="https://user-images.githubusercontent.com/22353987/218113710-779e5f56-a2a2-4a8e-a5a4-014845cd9af6.png">

**Comment by ThatXliner** [comment]
Can reproduce

**Comment by mbtools** [comment]
sure, it's just a test that fails with 404s. 

just like your public test page 😉 
https://sindresorhus.com/github-markdown-css/

![image](https://github.com/sindresorhus/generate-github-markdown-css/assets/59966492/1d62980d-119a-4019-b73a-b95bcdabd444)
