### ISSUE TITLE
Primer Source files

### ISSUE THREAD

**Issue by Mottie** [sindresorhus/generate-github-markdown-css#4]
I know this generator uses GitHub's rendered stylesheet to obtain the resulting markdown CSS, but it might be better to use the provided source SCSS files in https://github.com/primer/markdown.

The result would need to be combined with the syntax highlighting style provided in a separate repository: https://github.com/primer/github-syntax-light.

**Comment by sindresorhus** [comment]
Why change something that is working. Feel free to create a new project doing that, but this one is done.
